# Generated by Django 3.1.3 on 2020-11-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(default='', max_length=1000)),
                ('publication_img', models.ImageField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.city')),
            ],
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ad_text', models.CharField(default='sample ad text', max_length=2000)),
                ('price', models.IntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.ad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.city')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.publication')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.publication'),
        ),
    ]
