# Generated by Django 3.1.3 on 2020-11-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.ad'),
            preserve_default=False,
        ),
    ]
