# Generated by Django 3.1.3 on 2020-11-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20201121_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_text', models.CharField(default='', max_length=1000)),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.adtype')),
            ],
        ),
    ]
